In [1]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

print(rand_vec)

[13  3 16  9 18 12 16 18  5  7  9 20 13 11 11]


In [2]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

print(arr_3x5)

[[ 5 14  9 19  2]
 [20 10  4 20 13]
 [ 2  1 20  8  8]]


In [3]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

# Print the shape of the array
print(arr_3x5.shape)

(3, 5)


In [4]:
import numpy as np

# Generate a random vector of size 15 with integers in the range 1-20
rand_vec = np.random.randint(low=1, high=21, size=15)

# Reshape the vector into a 3 by 5 array
arr_3x5 = rand_vec.reshape((3, 5))

# Replace the max value in each row with 0
for i in range(arr_3x5.shape[0]):
    max_index = np.argmax(arr_3x5[i])
    arr_3x5[i][max_index] = 0

print(arr_3x5)

[[12  0 11  9  3]
 [ 2 11 13  0  2]
 [ 3 14  3  0  8]]


In [5]:
import numpy as np

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
arr_4x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)

# Print the shape of the array
print("Shape of the array:", arr_4x3.shape)

# Print the type of the array
print("Type of the array:", type(arr_4x3))

# Print the data type of the array
print("Data type of the array:", arr_4x3.dtype)

# Print the array
print(arr_4x3)

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np

# Define the square array
arr = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)

Eigenvalues: [2. 1.]
Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
import numpy as np

# Define the array
arr = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of the diagonal elements
diagonal_sum = np.trace(arr)

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:", diagonal_sum)

Sum of the diagonal elements: 4
